default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: mmakogin
  password: misyo1998

development:
  <<: *default
  database: opendota_development

test:
  <<: *default
  database: opendota_test
